version: 2.0

jobs:
  prepare:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Prepare
          command: |
            echo "Prepare"
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Test
          command: |
            echo "Test"
  deploy_staging:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Deploy staging
          command: |
            echo "Deploy staging"
  deploy_production:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Deploy production
          command: |
            echo "Deploy production"

parameters:
  skip_tests_and_deploy_staging_and_production:
    type: boolean
    default: false

workflows:
  version: 2

  all:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - deploy_staging:
          requires:
            - test
      - deploy_production:
          requires:
            - deploy_staging

  deploy_staging_and_production:
    #when: << pipeline.parameters.skip_tests_and_deploy_staging_and_production >>
    jobs:
      - prepare
      - deploy_staging:
          requires:
            - prepare
      - deploy_production:
          requires:
            - deploy_staging
