version: 2.1

jobs:
  prepare:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Prepare
          command: |
            echo "Prepare"
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Test
          command: |
            echo "Test"
  deploy_staging:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Deploy staging
          command: |
            echo "Deploy staging"
  deploy_production:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Deploy production
          command: |
            echo "Deploy production"

parameters:
  run_tests:
    type: boolean
    default: true
  run_staging_deploy:
    type: boolean
    default: true

workflows:
  version: 2

  all:
    jobs:
      - prepare
      - test:
          when: << pipeline.parameters.run_tests >>
          requires:
            - prepare
      - deploy_staging:
          when: << pipeline.parameters.run_staging_deploy >>
          requires:
            - test
      - deploy_production:
          requires:
            - deploy_staging
