version: 2.0

jobs:
  prepare:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Prepare
          command: |
            echo "Prepare"
  test:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Test
          command: |
            echo "Test"
  deploy_staging:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Deploy staging
          command: |
            echo "Deploy staging"
  deploy_production:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Deploy production
          command: |
            echo "Deploy production"

workflows:
  version: 2

  all:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - deploy_staging:
          requires:
            - test
      - deploy_production:
          requires:
            - deploy_staging
