version: 2.1

jobs:
  prepare:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Prepare
          command: |
            echo "Prepare"
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Test
          command: |
            echo "Test"
  deploy_staging:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Deploy staging
          command: |
            echo "Deploy staging"
  deploy_production:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Deploy production
          command: |
            echo "Deploy production"

parameters:
  only_deploy_staging:
    type: boolean
    default: false
  only_deploy_production:
    type: boolean
    default: false

workflows:
  version: 2

  all:
    jobs:
      - prepare
      - test:
          unless: << pipeline.parameters.only_deploy_staging || pipeline.parameters.only_deploy_production >>
          requires:
            - prepare
      - deploy_staging:
          unless: << pipeline.parameters.only_deploy_production >>
          requires:
            - test
      - deploy_production:
          unless: << pipeline.parameters.only_deploy_staging >>
          requires:
            - deploy_staging
